"use client";
import { useRef, useState } from "react";
import type { StoredAnalysis } from "@/lib/types";

function Header() { return <nav className="nav shell"><div className="brand">provenn<span>.</span></div><a className="pill" href="/verify">Verify a document</a></nav>; }
export default function Home() {
  const input = useRef<HTMLInputElement>(null); const [item, setItem] = useState<StoredAnalysis | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [proof, setProof] = useState<{transactionHash?:string;owner?:string;timestamp?:number}|null>(null);
  async function upload(file?: File) { if (!file) return; setLoading(true); setError(""); const data = new FormData(); data.append("file", file); const res = await fetch("/api/analyze", { method:"POST", body:data }); const json = await res.json(); setLoading(false); if (!res.ok) return setError(json.error); setItem(json); }
  async function secure() { if (!item) return; const res = await fetch("/api/proofs/managed", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({id:item.id}) }); const json = await res.json(); if (!res.ok) setError(json.error); else setProof(json.proof); }
  if (item) return <><Header/><main className="results shell"><div className="result-head"><div><div className="eyebrow">Analysis complete</div><h1>{item.analysis.title}</h1><p className="muted">{item.fileName} · {item.analysis.contractType}</p></div><div className="score">{item.analysis.healthScore}</div></div><div className="actions"><a className="secondary" href={`/api/reports/${item.id}`}>Download report</a><button className="primary" onClick={secure}>{proof ? "Proof secured" : "Secure on Monad"}</button></div>{proof && <p className="tag">Immutable proof recorded · {proof.transactionHash?.slice(0,12)}…</p>}<section className="grid"><article className="card wide"><div className="eyebrow">Contract summary</div><p>{item.analysis.summary}</p></article><article className="card"><h3>Parties</h3>{item.analysis.parties.map(x=><p className="muted" key={x}>{x}</p>)}</article><article className="card"><h3>Payment terms</h3>{item.analysis.paymentTerms.map(x=><p className="muted" key={x}>{x}</p>)}</article><article className="card"><h3>Important dates</h3>{item.analysis.keyDates.map(x=><p className="muted" key={x}>{x}</p>)}</article><article className="card"><h3>Obligations</h3>{item.analysis.obligations.map(x=><p className="muted" key={x}>{x}</p>)}</article><article className="card wide"><div className="eyebrow">Clause navigator</div><h2>What needs your attention</h2>{item.analysis.risks.map(r=><div className={`card risk ${r.severity}`} key={r.title}><div className="tag">{r.severity.toUpperCase()} RISK · {r.sectionReference || "Section reference unavailable"}</div><h3>⚠ {r.title}</h3><div className="quote">“{r.quotedClause}”</div><h4>Why this matters</h4><p className="muted">{r.whyItMatters}</p><p><b>Recommendation:</b> {r.recommendation}</p></div>)}</article><article className="card"><h3>Missing clauses</h3>{item.analysis.missingClauses.map(x=><p className="muted" key={x}>{x}</p>)}</article><article className="card"><h3>Recommendations</h3>{item.analysis.recommendations.map(x=><p className="muted" key={x}>{x}</p>)}</article></section>{error && <p>{error}</p>}</main></>;
  return <><Header/><main className="shell"><section className="hero"><div className="eyebrow">Contract intelligence, with proof</div><h1>Understand every contract in seconds.</h1><p>AI explains legal documents in plain English while Monad guarantees the integrity of every version.</p><div className="actions"><button className="primary" onClick={()=>input.current?.click()}>Upload contract</button><a className="secondary" href="/verify">Verify document</a></div></section><section className="features"><article className="card"><div className="eyebrow">01</div><h3>AI analysis</h3><p>Plain-language summaries of complex agreements.</p></article><article className="card"><div className="eyebrow">02</div><h3>Risk detection</h3><p>Navigate the clauses that deserve attention.</p></article><article className="card"><div className="eyebrow">03</div><h3>Immutable proof</h3><p>Prove the exact document version on Monad.</p></article></section><section className="upload"><div className="drop"><div className="eyebrow">Private by design</div><h2>{loading ? "Analyzing with AI…" : "Drop a contract here"}</h2><p className="muted">PDF, DOCX or TXT · up to 15 MB</p><button className="primary" disabled={loading} onClick={()=>input.current?.click()}>{loading ? "Reading document…" : "Choose file"}</button><input ref={input} hidden type="file" accept=".pdf,.docx,.txt,text/plain,application/pdf" onChange={e=>upload(e.target.files?.[0])}/>{error && <p>{error}</p>}</div></section></main><footer className="footer"><div className="shell">Provenn AI · Understand every contract. Prove every version.</div></footer></>;
}
